# Generated by Django 5.1.3 on 2024-11-20 14:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bidding', '0002_rename_start_bid_auction_starting_bid_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='auction',
            old_name='starting_bid',
            new_name='price',
        ),
        migrations.RemoveField(
            model_name='auction',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='auction',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='auction',
            name='end_date',
            field=models.DateTimeField(default=(20, 11, 2024)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='auction',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='auction',
            name='seller',
            field=models.ForeignKey(default=20241120, on_delete=django.db.models.deletion.CASCADE, to='bidding.userprofile'),
            preserve_default=False,
        ),
    ]
