# Generated by Django 5.1.3 on 2024-12-08 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bidding', '0003_auction_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='bidder_name',
        ),
        migrations.AddField(
            model_name='bid',
            name='bidder',
            field=models.ForeignKey(default=2004, on_delete=django.db.models.deletion.CASCADE, to='bidding.userprofile'),
            preserve_default=False,
        ),
    ]
