# Generated by Django 5.1.4 on 2024-12-19 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bidding', '0006_bid_role_userprofile_payment_info_userprofile_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='bid_type',
            field=models.CharField(choices=[('Up', 'Up'), ('Down', 'Down')], default='Up', max_length=10),
        ),
    ]
