# Generated by Django 5.1.4 on 2024-12-20 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bidding', '0007_bid_bid_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='poster',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.RemoveField(
            model_name='bid',
            name='role',
        ),
        migrations.AddField(
            model_name='auction',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='winning_auctions', to='bidding.userprofile'),
        ),
        migrations.AddField(
            model_name='auction',
            name='winner_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Job',
        ),
    ]
