# Generated by Django 5.1.5 on 2025-02-05 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bidding', '0009_alter_servicerequest_service_type_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='birth_date',
        ),
    ]
