name: Deno CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Deno
      uses: denoland/setup-deno@v2
      with:
        deno-version: v1.x
        node-version: '20'  # Update Node.js version to 20

    - name: Lint code
      run: deno lint

    - name: Run tests
      run: deno test
