name: Jekyll Docker

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Jekyll and Dependencies
        run: |
          gem install bundler jekyll
          bundle install

      - name: Build Jekyll Site
        run: bundle exec jekyll build
